### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by justinormont** [lqdev/mlnetacidemo#1]
Repo is missing a license file. Having the license file will help this repo spread. I'd recommend a MIT license, which is what my personal repos are under, along with our [ML.NET repo](https://github.com/dotnet/machinelearning). Expanding the README.md with parts (or the full demo) from your blog will also help it spread. 

Fantastic work, btw.

**Comment by lqdev** [comment]
Thanks for the tips! I'll work on getting those set up.

**Comment by lqdev** [comment]
Fixed in latest commit.
